//
//  StringConstants.swift
//  FamilyTime
//
//  Created by Usama-Apps on 09/09/2022.
//  Copyright © 2022 YumyApps. All rights reserved.
//

import Foundation

class CoredataKeys {
    
    //MARK: - CONSTANTS & KEYS
    class Keys : CoredataKeys {
        static let CHILD_ID                                     = "child_id"
        static let PACKAGE_ID                                   = "package_id"
        static let PACKAGE_NAME                                 = "package_name"
        static let DEVICE                                       = "device"
        static let BIRTHDAY                                     = "birthday"
        static let RELATIONSHIP                                 = "relationship"
        static let PLATFORM_ID                                  = "plateform_id"
        static let PLAN_ID                                      = "plan_id"
        static let PACKAGE                                      = "package"
        static let GENDER                                       = "gender"
        static let NAME                                         = "name"
        static let EMAIL                                        = "email"
        static let ID                                           = "id"
        static let PHONE                                        = "phone"
        static let createdAt                                    = "createdAt"
        static let updatedAt                                    = "updatedAt"
        static let LANGUAGE                                     = "language"
        static let PLAN                                         = "plan"
        static let END_DATE                                     = "end_date"
        static let CREATED_AT                                   = "created_at"
        static let DURATION                                     = "duration"
        static let EXPARIY_DATE                                 = "expiry_date"
        static let REMAINING_DAYS                               = "remaining_days"
        static let COVER_IMG_SRC                                = "cover_img_src"
        static let PROFILE_IMG_SRC                              = "profile_img_src"
        static let COLOR                                        = "color"
        static let PHONE_LOCK_STATUS                            = "phonelock_status"
        static let ACTIVE                                       = "active"
        static let DELETED                                      = "deleted"
        static let DELETED_BY                                   = "deleted_by"
        static let SUPER_USER_ID                                = "super_user_id"
        static let ACTIVATION_CODE                              = "activation_code"
        static let DATE_CREATED                                 = "date_created"
        static let date_modified                                = "date_modified"
        static let PUSH_TOKEN                                   = "push_token"
        static let CHILD_ENROLLED                               = "child_enrolled"
        static let CHILD_MDM_HASH                               = "child_mdm_hash"
        static let IS_PRODUCTION_BUILD                          = "is_production_build"
        static let VERSION_NUMBER                               = "version_number"
        static let VERSION_CODE                                 = "version_code"
        static let SUBSCRIPTION_ID                              = "subscription_id"
        static let SCHOOL_ID                                    = "school_id"
        static let CAMPUS_ID                                    = "campus_id"
        static let CLASS_ID                                     = "class_id"
        static let RESELLER_ID                                  = "reseller_id"
        static let TIME_ZONE                                    = "time_zone"
        static let IS_FORGET_ME                                 = "is_forget_me"
        static let API_TOKEN                                    = "api_token"
        static let ACTIVATION_DATE                              = "activation_date"
        static let UPDATED_AT                                   = "updated_at"
        static let UNIQUE_DEVICE_ID                             = "unique_device_id"
        static let AGENT                                        = "agent"
        static let NEW_SUBSCRIPTION_ID                          = "new_subscription_id"
        static let PRIORITY                                     = "priority"
        static let STATUS                                       = "status"
        static let TYPE                                         = "type"
        static let CONFIG_NAME                                  = "configName"
        static let CONFIG_VALUE                                 = "configValue"
        static let KEY_VALUE                                    = "keyValue"
        static let platformId                                   = "plateformID"
        static let PLATEFORM                                    = "plateform"
        static let START_DATE                                   = "start_date"
        static let PSP                                          = "psp"
        static let PRODUCT                                      = "product"
        static let VALUE                                        = "value"
        static let REMAINING                                    = "remaining"
        static let REMAINING_LIMIT                              = "remaining_limit"
        static let AUTO_ADD                                     = "auto_add"
        static let IS_ACTIVE                                    = "is_active"
        static let USER_ID                                      = "user_id"
        static let IS_JOINED                                    = "is_joined"
        static let IS_SUPER_PARENT                              = "is_super_parent"
        
        //MARK: Account Data
        static let EMAIL_COMPLAINT_ACCOUNT_DATA                 = "email_complaint_AccountData"
        static let EMAIL_BOUNCE_ACCOUNT_DATA                    = "email_bounce_AccountData"
        static let EMAIL_VERIFIED_AT_ACCOUNT_DATA               = "email_verified_at_AccountData"
        
        
        //MARK: Co Parent
        static let ACTIVE_CO_PARENT                             = "active_co_parent"
        static let COLOR_CO_PARENT                              = "color_co_parent"
        static let EMAIL_CO_PARENT                              = "email_co_parent"
        static let GENDER_CO_PARENT                             = "gender_co_parent"
        static let IS_JOINED_CO_PARENT                          = "is_joined_co_parent"
        static let IS_SUPER_PARENT_CO_PARENT                    = "is_super_parent_co_parent"
        static let LANGUAGE_CO_PARENT                           = "language_co_parent"
        static let NAME_CO_PARENT                               = "name_co_parent"
        static let RELATIONSHIP_CO_PARENT                       = "relationship_co_parent"
        static let TYPE_CO_PARENT                               = "type_co_parent"
        static let USER_ID_CO_PARENT                            = "user_id_co_parent"
        static let DELETED_CO_PARENT                            = "deleted_co_parent"
        
        //MARK: Co Parent Settings
        static let STATUS_CP_SETTINGS                           = "status_cp_settings"
        static let USER_ID_CP_SETTING                           = "user_id_cp_settings"
        static let TYPE_CP_SETTINGS                             = "type_cp_settings"
        static let ID_CP_SETTINGS                               = "id_cp_settings"
        static let DISPLAY_NAME_CP_SETTINGS                     = "id_cp_settings"
        
        //MARK: Preferences
        static let CHILD_ID_PREFERENCE                          = "child_id_pref"
        static let NAME_PREFERENCE                              = "name_pref"
        static let VALUE_PREFERENCE                             = "value_pref"
        static let STATUS_PREFERENCE                            = "status_pref"
        
        //MARK: DAILY LIMITS
        static let AUTO_ADD_DAILY_LIMIT                         = "auto_add_dailyLimit"
        static let CHILD_ID_DAILY_LIMIT                         = "child_id_dailyLimit"
        static let DURATION_DAILY_LIMIT                         = "duration_dailyLimit"
        static let IS_ACTIVE_DAILY_LIMIT                        = "is_active_dailyLimit"
        static let REMAINING_DAILY_LIMIT                        = "remaining_dailyLimit"
        static let REMAINING_LIMIT_DAILY_LIMIT                  = "remaining_limit_dailyLimit"
        
        //MARK: Child Info
        static let ACTIVATION_CODE_CHILD_INFO                   = "activation_code_child_info"
        static let ACTIVATION_DATE_CHILD_INFO                   = "activation_date_child_info"
        static let ACTIVE_CHILD_INFO                            = "active_child_info"
        static let AGENT_CHILD_INFO                             = "agent_child_info"
        static let API_TOKEN_CHILD_INFO                         = "api_token_child_info"
        static let APP_BUILD_CHILD_INFO                         = "app_build_child_info"
        static let APP_VERSION_CHILD_INFO                       = "app_version_child_info"
        static let BATTERY_REMAINING_CHILD_INFO                 = "battery_remaining_child_info"
        static let BIRTHDAY_CHILD_INFO                          = "birthday_child_info"
        static let CAMPUS_ID_CHILD_INFO                         = "campus_id_child_info"
        static let CHILD_ENROLLED_CHILD_INFO                    = "child_enrolled_child_info"
        static let CHILD_ID_CHILD_INFO                          = "child_id_child_info"
        static let CHILD_MDM_HASH_CHILD_INFO                    = "child_mdm_hash_child_info"
        static let CLASS_ID_CHILD_INFO                          = "class_id_child_info"
        static let COLOR_CHILD_INFO                             = "color_child_info"
        static let COVER_IMG_SRC_CHILD_INFO                     = "cover_img_src_child_info"
        static let CREATED_AT_CHILD_INFO                        = "created_at_child_info"
        static let DATE_CREATED_CHILD_INFO                      = "date_created_child_info"
        static let DATE_MODIFIED_CHILD_INFO                     = "date_modified_child_info"
        static let DELETED_BY_CHILD_INFO                        = "deleted_by_child_info"
        static let DEVICE_CHILD_INFO                            = "device_child_info"
        static let DEVICE_ID_CHILD_INFO                         = "device_id_child_info"
        static let DEVICE_IMEI_CHILD_INFO                       = "device_imei_child_info"
        static let DEVICE_LANGUAGE_CHILD_INFO                   = "device_language_child_info"
        static let DEVICE_MENUFACTURED_CHILD_INFO               = "device_manufacturer_child_info"
        static let DEVICE_MODEL_CHILD_INFO                      = "device_model_child_info"
        static let DEVICE_NAME_CHILD_INFO                       = "device_name_child_info"
        static let DEVICE_OS_CHILD_INFO                         = "device_os_child_info"
        static let DEVICE_TIME_ZONE_CHILD_INFO                  = "device_timezone_child_info"
        static let DURATION_CHILD_INFO                          = "duration_child_info"
        static let EMAIL_CHILD_INFO                             = "email_child_info"
        static let EXPAIRY_CHILD_INFO                           = "expiry_date_child_info"
        static let GENDER_CHILD_INFO                            = "gender_child_info"
        static let IS_FOGET_ME_CHILD_INFO                       = "is_forget_me_child_info"
        static let IS_PRODUCTION_BUILD_CHILD_INFO               = "is_production_build_child_info"
        static let NAME_CHILD_INFO                              = "name_child_info"
        static let NEW_SUBSCRIPTION_CHILD_INFO                  = "new_subscription_id_child_info"
        static let PACKAGE_CHILD_INFO                           = "package_child_info"
        static let PACKAGE_ID_CHILD_INFO                        = "package_id_child_info"
        static let PHONE_CHILD_INFO                             = "phone_child_info"
        static let PHONE_LOCK_STATUS_CHILD_INFO                 = "phonelock_status_child_info"
        static let PLAN_ID_CHILD_INFO                           = "plan_id_child_info"
        static let PLATEFORM_ID_CHILD_INFO                      = "plateform_id_child_info"
        static let PRIORITY_CHILD_INFO                          = "priority_child_info"
        static let PROFILE_IMG_SRC_CHILD_INFO                   = "profile_img_src_child_info"
        static let PUSH_TOKEN_CHILD_INFO                        = "push_token_child_info"
        static let RELATIONSHIP_CHILD_INFO                      = "relationship_child_info"
        static let REMAINING_DAYS_CHILD_INFO                    = "remaining_days_child_info"
        static let RESELLER_ID_CHILD_INFO                       = "reseller_id_child_info"
        static let SCHOOL_ID_CHILD_INFO                         = "school_id_child_info"
        static let SUBSCRIPTION_ID_CHILD_INFO                   = "subscription_id_child_info"
        static let SUPER_USER_ID_CHILD_INFO                     = "super_user_id_child_info"
        static let TIME_ZONE_CHILD_INFO                         = "time_zone_child_info"
        static let UNIQUE_DEVICE_ID_CHILD_INFO                  = "unique_device_id_child_info"
        static let UPDATED_AT_CHILD_INFO                        = "updated_at_child_info"
        static let VERSION_CODE_CHILD_INFO                      = "version_code_child_info"
        static let VERSION_NUMBER_CHILD_INFO                    = "version_number_child_info"
        static let WIFI_NAME_CHILD_INFO                         = "wifi_name_child_info"
        static let DELETED_CHILD_INFO                           = "deleted_child_info"
        
        //MARK: Child Info Dashboard
        static let ACTIVATION_CODE_DASHBOARD                   = "activation_code_DASHBOARD"
        static let ACTIVATION_DATE_DASHBOARD                   = "activation_date_DASHBOARD"
        static let ACTIVE_DASHBOARD                           = "active_DASHBOARD"
        static let AGENT_DASHBOARD                             = "agent_DASHBOARD"
        static let API_TOKEN_DASHBOARD                         = "api_token_DASHBOARD"
        static let APP_BUILD_DASHBOARD                        = "app_build_DASHBOARD"
        static let APP_VERSION_DASHBOARD                      = "app_version_DASHBOARD"
        static let BATTERY_REMAINING_DASHBOARD                = "battery_remaining_DASHBOARD"
        static let BIRTHDAY_DASHBOARD                          = "birthday_DASHBOARD"
        static let CAMPUS_ID_DASHBOARD                        = "campus_id_DASHBOARD"
        static let CHILD_ENROLLED_DASHBOARD                    = "child_enrolled_DASHBOARD"
        static let CHILD_ID_DASHBOARD                        = "child_id_DASHBOARD"
        static let CHILD_MDM_HASH_DASHBOARD                   = "child_mdm_hash_DASHBOARD"
        static let CLASS_ID_DASHBOARD                          = "class_id_DASHBOARD"
        static let COLOR_DASHBOARD                            = "color_DASHBOARD"
        static let COVER_IMG_SRC_DASHBOARD                     = "cover_img_src_DASHBOARD"
        static let CREATED_AT_DASHBOARD                        = "created_at_DASHBOARD"
        static let DATE_CREATED_DASHBOARD                     = "date_created_DASHBOARD"
        static let DATE_MODIFIED_DASHBOARD                     = "date_modified_DASHBOARD"
        static let DELETED_BY_DASHBOARD                        = "deleted_by_DASHBOARD"
        static let DEVICE_DASHBOARD                            = "device_DASHBOARD"
        static let DEVICE_ID_DASHBOARD                         = "device_id_DASHBOARD"
        static let DEVICE_IMEI_DASHBOARD                      = "device_imei_DASHBOARD"
        static let DEVICE_LANGUAGE_DASHBOARD                  = "device_language_DASHBOARD"
        static let DEVICE_MENUFACTURED_DASHBOARD               = "device_manufacturer_DASHBOARD"
        static let DEVICE_MODEL_DASHBOARD                      = "device_model_DASHBOARD"
        static let DEVICE_NAME_DASHBOARD                      = "device_name_DASHBOARD"
        static let DEVICE_OS_DASHBOARD                         = "device_os_DASHBOARD"
        static let DEVICE_TIME_ZONE_DASHBOARD                 = "device_timezone_DASHBOARD"
        static let DURATION_DASHBOARD                          = "duration_DASHBOARD"
        static let EMAIL_DASHBOARD                             = "email_DASHBOARD"
        static let EXPAIRY_DASHBOARD                           = "expiry_date_DASHBOARD"
        static let GENDER_DASHBOARD                           = "gender_DASHBOARD"
        static let IS_FOGET_ME_DASHBOARD                      = "is_forget_me_DASHBOARD"
        static let IS_PRODUCTION_BUILD_DASHBOARD               = "is_production_build_DASHBOARD"
        static let NAME_DASHBOARD                             = "name_DASHBOARD"
        static let NEW_SUBSCRIPTION_DASHBOARD                 = "new_subscription_id_DASHBOARD"
        static let PACKAGE_DASHBOARD                          = "package_DASHBOARD"
        static let PACKAGE_ID_DASHBOARD                       = "package_id_DASHBOARD"
        static let PHONE_DASHBOARD                             = "phone_DASHBOARD"
        static let PHONE_LOCK_STATUS_DASHBOARD                = "phonelock_status_DASHBOARD"
        static let PLAN_ID_DASHBOARD                          = "plan_id_DASHBOARD"
        static let PLATEFORM_ID_DASHBOARD                      = "plateform_id_DASHBOARD"
        static let PRIORITY_DASHBOARD                          = "priority_DASHBOARD"
        static let PROFILE_IMG_SRC_DASHBOARD                 = "profile_img_src_DASHBOARD"
        static let PUSH_TOKEN_DASHBOARD                       = "push_token_DASHBOARD"
        static let RELATIONSHIP_DASHBOARD                      = "relationship_DASHBOARD"
        static let REMAINING_DAYS_DASHBOARD                   = "remaining_days_DASHBOARD"
        static let RESELLER_ID_DASHBOARD                      = "reseller_id_DASHBOARD"
        static let SCHOOL_ID_DASHBOARD                         = "school_id_DASHBOARD"
        static let SUBSCRIPTION_ID_DASHBOARD                 = "subscription_id_DASHBOARD"
        static let SUPER_USER_ID_DASHBOARD                     = "super_user_id_DASHBOARD"
        static let TIME_ZONE_DASHBOARD                         = "time_zone_DASHBOARD"
        static let UNIQUE_DEVICE_ID_DASHBOARD                  = "unique_device_id_DASHBOARD"
        static let UPDATED_AT_DASHBOARD                        = "updated_at_DASHBOARD"
        static let VERSION_CODE_DASHBOARD                      = "version_code_DASHBOARD"
        static let VERSION_NUMBER_DASHBOARD                    = "version_number_DASHBOARD"
        static let WIFI_NAME_DASHBOARD                         = "wifi_name_DASHBOARD"
        static let DELETED_DASHBOARD                           = "deleted_DASHBOARD"
        
        //MARK: APP HOSTORY KEYS
        static let B_BROWSERHITORY_ID                          = "browsinghistory_id"
        static let B_CHILD_ID                                  = "child_id"
        static let B_CREATED_AT                                = "created_at"
        static let B_DELETED                                   = "deleteds"
        static let B_DOMAIN                                    = "domain"
        static let B_NUMBER_VISTIT                             = "number_visits"
        static let B_SUPER_USER_ID                             = "super_user_id"
        static let B_TIME_VIST                                 = "time_visits"
        static let B_TITLE                                     = "title"
        static let B_UPDATED_AT                                = "updated_at"
        static let B_URL                                       = "url"
        
        //MARK: YOUTUBE HISTORY KEYS
        static let Y_ID                                        = "id"
        static let Y_CHILD_ID                                  = "child_id"
        static let Y_CREATED_AT                                = "created_at"
        static let Y_DELETED                                   = "deleteds"
        static let Y_DOMAIN                                    = "domain"
        static let Y_NUMBER_VISTIT                             = "number_visits"
        static let Y_SUPER_USER_ID                             = "super_user_id"
        static let Y_TIME_VIST                                 = "time_visit"
        static let Y_TITLE                                     = "title"
        static let Y_UPDATED_AT                                = "updated_at"
        static let Y_URL                                       = "url"
        
        //MARK: TOKTOK HISTORY KEYS
        static let T_ID                                        = "id"
        static let T_CHILD_ID                                  = "child_id"
        static let T_CREATED_AT                                = "created_at"
        static let T_DELETED                                   = "deleteds"
        static let T_DOMAIN                                    = "domain"
        static let T_NUMBER_VISTIT                             = "number_visits"
        static let T_SUPER_USER_ID                             = "super_user_id"
        static let T_TIME_VIST                                 = "time_visit"
        static let T_TITLE                                     = "title"
        static let T_UPDATED_AT                                = "updated_at"
        static let T_URL                                       = "url"
    }
    
    //MARK: - FILE
    class Entities: CoredataKeys {
        static let PACKAGE_FILE                                 = "Package"
        static let CONFIGURATION_FILE                           = "Configuration_DB"
        static let BILLING_DATA_FILE                            = "BillingSubscription"
        static let ACCOUNT_DATA_FILE                            = "AccountData"
        static let DAILY_LIMIT_FILE                             = "Daily_Limit"
        static let CHILD_INFO_FILE                              = "Children_Info"
        static let PREFERENCE_FILE                              = "Child_Preferences"
        static let CO_PARENT_FILE                               = "Co_Parent"
        static let CO_PARENT_SETTINGS                           = "Co_Parent_Settings"
        static let CHILD_INFO_DASHBOARD                         = "Child_Info_Dashboard"
        static let APP_HISTORY_DATA                             = "History_Data"
        static let APP_YOUTUBE_DATA                             = "Youtube_History"
        static let APP_TIKTOK_DATA                              = "Tiktok_History"
        static let SOCIAL_HISTORY_DATA                          = "Social_History"
        static let TEXT_MSGS_DATA                               = "TextMessages"
    }
    
    
    //MARK: - FILE
    class SettingKey: CoredataKeys {
        static let SETTING_CALL_LOGS                            = "call_logs"
        static let SETTING_SMS_LOGS                             = "sms_logs"
        static let SETTING_CONTACT_LOGS                         = "contact_logs"
        static let SETTING_LOCATION_TRACK                       = "location_tracking"
        static let SETTING_INSTALL_APP                          = "installed_app_logs"
        static let SETTING_SAFE_INTERNET                        = "safe_internet"
        static let SETTING_WEB_HISTORY                          = "web_history"
        static let SETTING_YOUTUBE_HISTORY                      = "yotutube_history"
        static let SETTING_TIKTOK_HISTORY                       = "tiktok_history"
        static let SETTING_PLACE_ALERT                          = "monitor_places"
        static let SETTING_BLOCK_ALERT                          = "app_blocking"
        static let SETTING_WATCHLIST_ALERT                      = "contact_watchlist"
        static let SETTING_TOP_STACK                            = "top_stack"
    }
}
