//
//  UserDefaultsConstants.swift
//  FamilyTime
//
//  Created by Usama-Apps on 13/09/2022.
//  Copyright © 2022 YumyApps. All rights reserved.
//

import Foundation

class UserDefaultsConstants {
    
    static let SHOPPING_FUNNEL_NAME             = "shopping_funnel_name"
    static let SHOPPING_FUNNEL_VALUE            = "shopping_funnel"
    static let UPGRADE_SUB_INTERNAL             = "upgrade_sub_int"
    static let UPDRADE_SUB_EXTERNAL             = "upgrade_sub_ext"
    static let APPLE_TRIAL_INT                  = "trial_sub_int"
    static let FAST_SPRING_TRIAL_EXT            = "trial_sub_ext"
    static let CHILD_COUNT                      = "child_count_value"
    static let SET_UP_COMPLETE                  = "setup_complete_key"
    static let BILLING_STATUS                   = "billing_status"
    static let SELECTED_CHILD_ID                = "selectedChildId"
    static let FAMILY_MAP_ENABLE                = "familymapEnable"
    static let ACTIVATION_FUNNEL                = "activation_funnel"
    static let RELOAD_FROM_DETAILS_VC           = "LOAD_DASHBOARD_FROM_DETAILED_SCREEN"
    static let REFRESH_RELOADER                 = "refresh_loader"
    static let USER_LANGUAGE                    = "userlanguage"
    static let ZENDESK_CHAT_SCREEN              = "ZendeskChatScreen"
    static let SELECTED_CHILD_PACKAGE           = "SELECTED_CHILD_PACKAGE"
    static let ADD_NEW_CHILD                    = "ShouldAddNewChild"
    static let LAST_TIME_CLICKED_UPGRADE        = "upgradeButtonClicked"
    static let I_HAVE_DONE_INSTRUCTIONS         = "iHaveDoneInstructionsTitle"
    static let RELOAD_DASHBOARD_VIA_INSTRUCTION = "ReloadDashboardFromInstructions"
    static let IS_COMING_FROM_BROWSER_UPGRADE   = "isComingFromBrowserScreen"
    static let PRODUCT_ACCOUNT_ARRAY            = "PRODUCT_DATA"
    static let SUBSCRIPTION_RENEWAL_DATE        = "SUBSCRIPTION_RENEWAL_DATE"
    static let LAST_TIME_CLICKED_TRIAL          = "last_time_clicked_trial_upgrade_button"
    static let IS_COMING_FROM_BROWSER_TRIAL     = "is_coming_from_browser_trial"
    static let DISMISS_TRIAL_SCREEN             = "dismiss_trail_screen"
    static let USER_ID                          = "userID"
    static let USER_NAME                        = "userName"
    static let USER_EMAIL                       = "userEmail"
    static let USER_PHONE                       = "userPhone"
    static let USER_GENDER                      = "userGender"
    static let USER_RELATION                    = "userRelation"
    static let USER_TYPE                        = "userType"
    static let DRAWER_TYPE                      = "DRAWER_TYPE"
    static let CHILD_MDM_HASH                   = "CHILD_MDM_HASH"
    static let QR_CODE_STRING_VALUE             = "QR_CODE_STRING_VALUE"
    static let GENERATE_QR_CODE                 = "GENERATE_QR_CODE"
    static let EMAIL_VERIFIED_AT_ACCOUNT        = "Email_Verified_At_Account_Data"
    static let EMAIL_BOUNCE_ACCOUNT             = "Email_Bounce_Account_Data"
    static let EMAIL_COMPLAINT_ACCOUNT          = "Email_Complaint_Account_Data"
    static let HIT_EMAIL_VERIFICATOIN_API       = "HIT_EMAIL_VERIFICAION_API"
    static let DAILY_LIMIT_RELOAD_HOME          = "DAILY_LIMIT_CHECK"
    static let APPROVED_APP_TITLE               = "approve_app_TITLE"
    static let APPROVED_APP_BODY                = "approve_app_BODY"
    static let PICK_UP_PANIC_NOTIFICATON        = "pickup_panic"
    static let APPROVE_APP_NOTIFICAION          = "approve_app_TEST"
    static let APPROVE_APP_NAME                 = "approve_app_NAME"
    static let APPROVE_APP_PACKAGE_NAME         = "approve_app_PACKAGE"
    static let GEO_FENCE_NOTIFICATION           = "geo_fence_status"
    static let APP_BLOCK_STATUS                 = "app_blocking_status"
    static let APP_BLOCK_CHILD_NAME             = "app_block_child_name"
    static let EMAIL_VERIFIED_PUSH              = "EMAIL_VERIFIED_PUSH"
    static let PRODUCT_NAME_INTERNAL            = "PRODUCT_NAME_INTERNAL"
    static let PRODUCT_PRICE_INTERNAL           = "PRODUCT_PRICE_INTERNAL"
    static let PRODUCT_NAME_EXTERNAL            = "PRODUCT_NAME_EXTERNAL"
    static let PRODUCT_PRICE_EXTERNAL           = "PRODUCT_PRICE_EXTERNAL"
    static let PRODUCT_SUB_URL_EXTERNAL         = "PRODUCT_SUB_URL_EXTERNAL"
    static let FROM_DATA_USE_SCREEN             = "FROM_DATA_USE_SCREEN"
    static let SUBSCRIPTION_CREATED_PUSH        = "SUBSCRIPTION_CREATED_PUSH"
    static let CONTACT_WATCHLIST_PUSH           = "Contact_Watchlist_Push"
    static let UPDATE_HOME_DATA_WHILE_UPGRADE   = "UPDATE_HOME_DATA_WHILE_UPGRADE"
    static let HIT_SUBSCRIPTION_FAILED          = "HIT_SUBSCRIPTION_FAILED"
    static let SUBSCRIPTION_CHECK_KEY           = "SUBSCRIPTION_CHECK_KEY"
    static let SHOW_SUB_INT_NOTIFICATION        = "SHOW_SUB_INT_NOTIFICATION"
    static let SHOW_SUB_EXT_NOTIFICATION        = "SHOW_SUB_EXT_NOTIFICATION"
    static let SUBSCRIPTION_DONE_KEY            = "SUBSCRIPTION_DONE_KEY"
    static let APP_BLOCK_CONTACT_LIST_MSG       = "app_block_contact_watchlist_message"
    static let CHILD_CREATED_PUSH               = "CHILD_CREATED_PUSH"
    static let PHONE_LOCKED_PUSH                = "PHONE_LOCKED_PUSH"
    static let RELOAD_HOME_PUSH                 = "RELOAD_HOME_PUSH"
    static let PHONE_LOCKED                     = "PHONE_LOCKED"
    static let SELECTED_CHILD_VERSION_NUMBER    = "SELECTED_CHILD_VERSION_NUMBER"
}
